### ISSUE TITLE
Crash with NPM?

### ISSUE THREAD

**Issue by ghost** [SamVerschueren/gulp-cordova-icon#16]
Note: This is not due to the dep upgrades.

Using NPM  3.4 and NodeJS 4.1.2, the NPM being used by gulp-cordova (or dep) is crashing and is an old version of 2.10.

If I remove the gulp-cordova-icon from the pipe, the cordova build works. If I add it back, I get the error below.

```
async@1.5.0 .cordova\hooks\node_modules\async
[14:05:55] '<anonymous>' errored after 4.18 s
[14:05:55] ReferenceError: resolver is not defined
    at null._onTimeout (c:\git\pos\node_modules\gulp-cordova-icon\node_modules\npm\lib\install.js:840:7)
    at Timer.listOnTimeout (timers.js:92:15)
[14:05:55] 'cordova:debug' errored after 42 s
[14:05:55] ReferenceError: resolver is not defined
    at null._onTimeout (c:\git\pos\node_modules\gulp-cordova-icon\node_modules\npm\lib\install.js:840:7)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by SamVerschueren** [comment]
Thanks for reporting.

**Comment by SamVerschueren** [comment]
If this is related to `async`, it should be fixed in `0.3.0` because I removed that dependency. Care to test it again @robertbaker ?

**Comment by ghost** [comment]
It is because of async. I'll try to test it soon. Did you merge my dep. PR
as well?

**Comment by SamVerschueren** [comment]
Jep! Thanks for that one!

**Comment by ghost** [comment]
@SamVerschueren I cannot build right now because you did not bump the versions. I created issues in the repo's that need version bumped.

**Comment by SamVerschueren** [comment]
Jep, I saw :). Will do it today.

**Comment by SamVerschueren** [comment]
Fixed?

**Comment by ghost** [comment]
yes :)
